// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKbOW2SpMyhI6GzPSsyxsOTk9ena6RjeQ',
    appId: '1:102356954769:web:aa5c84b105f0243245d930',
    messagingSenderId: '102356954769',
    projectId: 'location-shower-8c2d5',
    authDomain: 'location-shower-8c2d5.firebaseapp.com',
    storageBucket: 'location-shower-8c2d5.appspot.com',
    measurementId: 'G-EKYQ3ES87Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1RwzCGqJb-7lUi1RUJbVCrSJr7E-aB_Q',
    appId: '1:102356954769:android:7d0238c75985efb645d930',
    messagingSenderId: '102356954769',
    projectId: 'location-shower-8c2d5',
    storageBucket: 'location-shower-8c2d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa7jc7Eu0ybpotk66cTYG2Sqdei4jFzRI',
    appId: '1:102356954769:ios:18be5d67dc57a2eb45d930',
    messagingSenderId: '102356954769',
    projectId: 'location-shower-8c2d5',
    storageBucket: 'location-shower-8c2d5.appspot.com',
    iosBundleId: 'com.example.locationTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa7jc7Eu0ybpotk66cTYG2Sqdei4jFzRI',
    appId: '1:102356954769:ios:18be5d67dc57a2eb45d930',
    messagingSenderId: '102356954769',
    projectId: 'location-shower-8c2d5',
    storageBucket: 'location-shower-8c2d5.appspot.com',
    iosBundleId: 'com.example.locationTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKbOW2SpMyhI6GzPSsyxsOTk9ena6RjeQ',
    appId: '1:102356954769:web:a268c6a8f1aea47445d930',
    messagingSenderId: '102356954769',
    projectId: 'location-shower-8c2d5',
    authDomain: 'location-shower-8c2d5.firebaseapp.com',
    storageBucket: 'location-shower-8c2d5.appspot.com',
    measurementId: 'G-1MXGJQQVCG',
  );
}
